export const techniqueRepresentativeProblemIds: Record<string, readonly string[]> = {
  "hash-map": ["two-sum", "contains-duplicate", "official-group-anagrams"],
  "stack": ["valid-parentheses", "official-min-stack", "official-evaluate-reverse-polish-notation"],
  "intervals": ["merge-intervals", "insert-interval", "non-overlapping-intervals"],
  "framework-thinking": [],
  "recursion-perspective": [],
  "two-pointers": ["three-sum", "official-two-sum-ii-input-array-is-sorted", "valid-palindrome"],
  "sliding-window": ["longest-substring-no-repeat", "minimum-window-substring", "official-permutation-in-string"],
  "binary-search": ["binary-search", "koko-bananas", "official-search-in-rotated-sorted-array"],
  "bfs": ["binary-tree-level-order", "rotting-oranges", "open-the-lock"],
  "dfs-backtracking": ["subsets", "combination-sum", "word-search"],
  "dynamic-programming": ["house-robber", "official-climbing-stairs", "coin-change"],
  "greedy": ["jump-game", "best-time-stock", "official-gas-station"],
  "divide-conquer": ["official-median-of-two-sorted-arrays"],
  "binary-tree-recursion": ["max-depth-tree", "official-invert-binary-tree", "official-balanced-binary-tree"],
  "prefix-sum": ["official-product-of-array-except-self"],
  "difference-array": [],
  "monotonic-stack": ["daily-temperatures", "car-fleet", "official-largest-rectangle-in-histogram"],
  "monotonic-queue": ["official-sliding-window-maximum"],
  "heap": ["top-k-frequent-elements", "k-closest-points", "official-kth-largest-element-in-an-array"],
  "complexity": [],
  "union-find": ["official-redundant-connection", "official-number-of-connected-components-in-an-undirected-graph", "official-graph-valid-tree"],
  "trie": ["official-implement-trie-prefix-tree", "official-design-add-and-search-words-data-structure", "official-word-search-ii"],
  "topological-sort": ["course-schedule", "official-course-schedule-ii", "official-alien-dictionary"],
  "graph-shortest-path": ["network-delay-time", "official-cheapest-flights-within-k-stops"],
  "minimum-spanning-tree": ["official-min-cost-to-connect-all-points"],
  "bit-manipulation": ["official-single-number", "official-number-of-1-bits", "official-sum-of-two-integers"],
  "fast-slow-pointers": ["linked-list-cycle", "remove-nth-from-end"],
  "design-data-structure": ["official-lru-cache", "official-design-twitter", "official-find-median-from-data-stream"],
  "knapsack-dp": ["partition-equal-subset-sum", "coin-change", "official-target-sum"],
  "state-machine-dp": ["best-time-stock", "official-best-time-to-buy-and-sell-stock-with-cooldown"],
  "interval-dp": ["official-burst-balloons"],
  "tree-dp": ["official-diameter-of-binary-tree", "official-binary-tree-maximum-path-sum"],
  "grid-traversal": ["number-of-islands", "rotting-oranges", "official-pacific-atlantic-water-flow"],
  "bitmask-dp": [],
  "digit-dp": [],
  "game-theory-dp": [],
  "kmp-string-matching": [],
  "segment-tree-bit": [],
  "simulation": ["official-spiral-matrix", "official-rotate-image", "official-set-matrix-zeroes"],
  "math-geometry": ["official-happy-number", "official-pow-x-n", "official-rotate-image"],
};

export function representativeProblemIdsFor(techniqueId: string) {
  return techniqueRepresentativeProblemIds[techniqueId] ?? [];
}
